### ISSUE TITLE
Use EZyRB with available state space matrices

### ISSUE THREAD

**Issue by SebiK91** [mathLab/EZyRB#122]
Hey everybody,

I am writing my master thesis and I'd like to do some model order reductions. One method I'd like to use is the POD and therefore I found the package EZyRB. I'd like to apply EZyRB on my data consisting of different inputs and outputs. How can I apply EZyRB to get the reduced order model?

Thanks and regards
Markus

**Comment by mtezzele** [comment]
Dear @SebiK91,
with our package you can indeed perform POD to your parametric problem. 
I suggest you to follow [tutorial 1](https://github.com/mathLab/EZyRB/blob/master/tutorials/tutorial-1.ipynb) and also to read the references you can find in the readme file.

Best,
Marco
