### ISSUE TITLE
sklearn version

### ISSUE THREAD

**Issue by mtezzele** [mathLab/EZyRB#149]
Specify in the readme the minimum version of sklearn in order to use the new regressors such as `NeighborsRegressor` (some attributes as `n_samples_fit_` exist only in the most recent versions).

**Comment by fAndreuzzi** [comment]
> Specify in the readme the minimum version of sklearn

Do you think `>=0.9` is ok?

> some attributes as `n_samples_fit_` exist only in the most recent versions

I don't know if I understand properly, isn't `n_samples_fit_` an integer attribute of `KNeighborsRegressor`, which was introduced in 0.9?

**Comment by mtezzele** [comment]
I was using scikit 0.21 and got this error: AttributeError: 'RadiusNeighborsRegressor' object has no attribute 'n_samples_fit_'
This is the old doc and I could not find the attribute above: https://scikit-learn.org/0.21/modules/generated/sklearn.neighbors.RadiusNeighborsRegressor.html#sklearn.neighbors.RadiusNeighborsRegressor
Regarding KNeighborsRegressor I had the same. Maybe I misread something?

**Comment by fAndreuzzi** [comment]
I created a virtualenv with `python=3.6.12`, then installed `scikit-learn==0.21.0` and EZyRB using:
`python -m pip install git+https://github.com/mathLab/EZyRB.git`
The following code works on my computer:
```
>>> reg = KNeighborsRegressor(n_neighbors=2, algorithm='kd_tree')
>>> reg.fit([[0],[1],[23]], [2,5,6])
>>> reg.predict([4])
array([3.5])
```
Am I missing something in your setup?

**Comment by mtezzele** [comment]
Ok I will investigate further what is missing in my env. I'm sorry for the trouble.

**Comment by fAndreuzzi** [comment]
Please let me know if I can provide further info about my environment.
