### ISSUE TITLE
Adding the files

### ISSUE THREAD

**Issue by rahulvigneswaran** [mathLab/EZyRB#80]
Hi @mtezzele ,

I ran the RANS simulation for a body and exported the `.vtk` files. But I have so many `.vtk` files. How can I identify which `.vtk` file corresponds to which parametric points ? I know it is a novice question, kindly help me out.

![image](https://user-images.githubusercontent.com/37276766/54692213-a508ef00-4b4a-11e9-9d4d-10504e80b25b.png)

**Comment by mtezzele** [comment]
Only issues related to the packages please.
